# Generated by Django 3.2.23 on 2024-01-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240128_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_pad',
            new_name='stripe_pid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='grand_total',
            new_name='total_cost_with_delivery',
        ),
    ]
