# Generated by Django 3.2.23 on 2024-01-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost_with_delivery',
            new_name='grand_total',
        ),
    ]
