# Generated by Django 3.2.23 on 2024-01-23 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Length (mm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weight (kg)')),
                ('magazine_capacity', models.PositiveIntegerField(verbose_name='Magazine Capacity (rounds)')),
                ('muzzle_velocity', models.PositiveIntegerField(verbose_name='Muzzle Velocity (FPS)')),
                ('power_system', models.CharField(choices=[('gas', 'Gas'), ('electric', 'Electric'), ('spring', 'Spring'), ('co2', 'CO2')], max_length=50, verbose_name='Powered By')),
                ('ammunition_type', models.CharField(choices=[('bb', 'BB'), ('pellet', 'Pellet')], max_length=50, verbose_name='Ammunition Type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.manufacturer')),
                ('specification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.specification')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='accessories', to='products.Product')),
            ],
        ),
    ]
