# Generated by Django 3.2.23 on 2024-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240123_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='related_product', to='products.Accessory'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ammunition_type',
            field=models.CharField(blank=True, choices=[('bb', 'BB'), ('pellet', 'Pellet')], max_length=50, null=True, verbose_name='Ammunition Type'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Length (mm)'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='magazine_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Magazine Capacity (rounds)'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='muzzle_velocity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Muzzle Velocity (FPS)'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='power_system',
            field=models.CharField(blank=True, choices=[('gas', 'Gas'), ('electric', 'Electric'), ('spring', 'Spring'), ('co2', 'CO2')], max_length=50, null=True, verbose_name='Powered By'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)'),
        ),
    ]
