# Generated by Django 3.2.23 on 2024-01-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_accessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='specification',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Min Length (mm)'),
        ),
    ]
