# Generated by Django 3.2.23 on 2024-01-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240123_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_spec',
        ),
        migrations.AddField(
            model_name='specification',
            name='related_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
