# Generated by Django 3.2.23 on 2024-01-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240124_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Length (mm)'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='related_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_spec', to='products.product'),
        ),
    ]
